/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Sat Mar 02 14:46:22 2019. */

#ifndef PB_FLOWSTATUS_PB_H_INCLUDED
#define PB_FLOWSTATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ValveStatus {
    bool has_pinNumber;
    int32_t pinNumber;
    bool has_isOn;
    bool isOn;
    bool has_isScheduled;
    bool isScheduled;
    bool has_flowTimeRemainingMs;
    int32_t flowTimeRemainingMs;
/* @@protoc_insertion_point(struct:ValveStatus) */
} ValveStatus;

typedef struct _FlowStatusMessage {
    bool has_valveStatus;
    ValveStatus valveStatus;
    bool has_maxRunTimeMs;
    int32_t maxRunTimeMs;
    bool has_mainValveRunTimeMs;
    int32_t mainValveRunTimeMs;
    bool has_mainValveIsOn;
    bool mainValveIsOn;
    bool has_mainValvePinNumber;
    int32_t mainValvePinNumber;
/* @@protoc_insertion_point(struct:FlowStatusMessage) */
} FlowStatusMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ValveStatus_init_default                 {false, 0, false, 0, false, 0, false, 0}
#define FlowStatusMessage_init_default           {false, ValveStatus_init_default, false, 0, false, 0, false, 0, false, 0}
#define ValveStatus_init_zero                    {false, 0, false, 0, false, 0, false, 0}
#define FlowStatusMessage_init_zero              {false, ValveStatus_init_zero, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ValveStatus_pinNumber_tag                1
#define ValveStatus_isOn_tag                     2
#define ValveStatus_isScheduled_tag              3
#define ValveStatus_flowTimeRemainingMs_tag      4
#define FlowStatusMessage_valveStatus_tag        1
#define FlowStatusMessage_maxRunTimeMs_tag       2
#define FlowStatusMessage_mainValveRunTimeMs_tag 3
#define FlowStatusMessage_mainValveIsOn_tag      4
#define FlowStatusMessage_mainValvePinNumber_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t ValveStatus_fields[5];
extern const pb_field_t FlowStatusMessage_fields[6];

/* Maximum encoded size of messages (where known) */
#define ValveStatus_size                         26
#define FlowStatusMessage_size                   63

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FLOWSTATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
