/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Mar 02 14:46:22 2019. */

#include "flowCommand.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FlowCommandMessage_fields[4] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, FlowCommandMessage, pinNumber, pinNumber, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, FlowCommandMessage, isOn, pinNumber, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, FlowCommandMessage, runTimeMs, isOn, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
