/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Dec 30 07:39:05 2018. */

#include "motion_detect.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MotionDetectMessage_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, MotionDetectMessage, expectedDistanceCm, expectedDistanceCm, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, MotionDetectMessage, triggeredDistanceCm, expectedDistanceCm, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
