/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Sun Dec 30 07:39:05 2018. */

#ifndef PB_MOTION_DETECT_PB_H_INCLUDED
#define PB_MOTION_DETECT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MotionDetectMessage {
    bool has_expectedDistanceCm;
    int32_t expectedDistanceCm;
    bool has_triggeredDistanceCm;
    int32_t triggeredDistanceCm;
/* @@protoc_insertion_point(struct:MotionDetectMessage) */
} MotionDetectMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MotionDetectMessage_init_default         {false, 0, false, 0}
#define MotionDetectMessage_init_zero            {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MotionDetectMessage_expectedDistanceCm_tag 1
#define MotionDetectMessage_triggeredDistanceCm_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MotionDetectMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define MotionDetectMessage_size                 22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MOTION_DETECT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
