/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Dec 29 19:34:01 2017. */

#include "weather.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t WeatherMessage_fields[3] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, WeatherMessage, temperatureF, temperatureF, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, WeatherMessage, humidity, temperatureF, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
