/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Fri Dec 29 19:34:01 2017. */

#ifndef PB_WEATHER_PB_H_INCLUDED
#define PB_WEATHER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _WeatherMessage {
    bool has_temperatureF;
    float temperatureF;
    bool has_humidity;
    float humidity;
/* @@protoc_insertion_point(struct:WeatherMessage) */
} WeatherMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define WeatherMessage_init_default              {false, 0, false, 0}
#define WeatherMessage_init_zero                 {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define WeatherMessage_temperatureF_tag          1
#define WeatherMessage_humidity_tag              2

/* Struct field encoding specification for nanopb */
extern const pb_field_t WeatherMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define WeatherMessage_size                      10

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEATHER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
